version: "3"

services:

  db:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: flairsou
      MYSQL_DATABASE: flairsou

  api:
    build: .
    depends_on: 
      - db
    environment: 
      SERVER_PORT: 3000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: flairsou
      DB_USER: root
      DB_PASSWD: flairsou
      DEBUG: flairsou:*
    ports: 
      - "3000:3000"
